/**
 * Table creation.
 */
CREATE TABLE BOOK (
  ISBN  CHARACTER(13) PRIMARY KEY,
  Title VARCHAR(255),
  Year  CHARACTER(4),
  Price DOUBLE
);

CREATE TABLE AUTHOR (
  Name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE CATEGORY (
  Name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE PUBLISHER (
  Name VARCHAR(100) PRIMARY KEY
);

CREATE TABLE BOOK_AUTHOR (
  Book_ISBN   CHARACTER(13) NOT NULL,
  Author_Name INTEGER       NOT NULL,
  PRIMARY KEY (Book_ISBN, Author_Name),
  FOREIGN KEY (Book_ISBN) REFERENCES Book (ISBN) ON DELETE CASCADE,
  FOREIGN KEY (Author_Name) REFERENCES AUTHOR (Name) ON DELETE CASCADE
);

CREATE TABLE BOOK_CATEGORY (
  Book_ISBN     CHARACTER(13) NOT NULL,
  Category_Name INTEGER       NOT NULL,
  PRIMARY KEY (Book_ISBN, Category_Name),
  FOREIGN KEY (Book_ISBN) REFERENCES Book (ISBN) ON DELETE CASCADE,
  FOREIGN KEY (Category_Name) REFERENCES CATEGORY (Name) ON DELETE CASCADE
);

CREATE TABLE BOOK_PUBLISHER (
  Book_ISBN      CHARACTER(13) NOT NULL,
  Publisher_Name INTEGER       NOT NULL,
  PRIMARY KEY (Book_ISBN, Publisher_Name),
  FOREIGN KEY (Book_ISBN) REFERENCES Book (ISBN) ON DELETE CASCADE,
  FOREIGN KEY (Publisher_Name) REFERENCES PUBLISHER (Name) ON DELETE CASCADE
);

CREATE TABLE CUSTOMER (
  Id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  First_Name         VARCHAR(20),
  Last_Name          VARCHAR(20),
  Email              VARCHAR(50) UNIQUE,
  Pass_Hash          CHARACTER(66), -- Store salted password for security reasons.
  Address_Id         INTEGER,
  Credit_Card_Number INTEGER,
  FOREIGN KEY (Address_Id) REFERENCES ADDRESS (Id),
  FOREIGN KEY (Credit_Card_Number) REFERENCES CREDIT_CARD (Credit_Card_Number)
);

CREATE TABLE ORDERS (
  Id            INTEGER PRIMARY KEY AUTOINCREMENT,
  Customer_Id   INTEGER,
  Book_ISBN     CHARACTER(13),
  Quantity      INTEGER,
  Purchase_Date DATETIME,
  FOREIGN KEY (Book_ISBN) REFERENCES Book (ISBN) ON DELETE SET NULL,
  FOREIGN KEY (Customer_Id) REFERENCES CUSTOMER (Id) ON DELETE CASCADE
);

CREATE TABLE WAREHOUSE (
  Id         INTEGER PRIMARY KEY,
  Address_Id INTEGER,
  FOREIGN KEY (Address_Id) REFERENCES ADDRESS (Id) ON DELETE CASCADE
);

CREATE TABLE BOOK_STOCK (
  Book_ISBN    CHARACTER(13),
  Warehouse_Id INTEGER,
  Quantity     INTEGER CHECK (Quantity >= 0),
  PRIMARY KEY (Book_ISBN, Warehouse_Id),
  FOREIGN KEY (Book_ISBN) REFERENCES BOOK (ISBN) ON DELETE CASCADE,
  FOREIGN KEY (Warehouse_Id) REFERENCES WAREHOUSE (Id) ON DELETE CASCADE
);


CREATE TABLE RATING (
  Customer_Id INTEGER,
  Book_ISBN   CHARACTER(13),
  Star_Count  INTEGER CHECK (Star_Count BETWEEN 1 AND 5),
  Comment     VARCHAR(400),
  PRIMARY KEY (Customer_Id, Book_ISBN),
  FOREIGN KEY (Customer_Id) REFERENCES CUSTOMER (Id) ON DELETE CASCADE,
  FOREIGN KEY (Book_ISBN) REFERENCES Book (ISBN) ON DELETE CASCADE
);

CREATE TABLE CREDIT_CARD (
  Credit_Card_Number INTEGER PRIMARY KEY,
  CVV_Code           INTEGER,
  Billing_Address_Id INTEGER,
  FOREIGN KEY (Billing_Address_Id) REFERENCES ADDRESS (Id) ON DELETE SET NULL
);

CREATE TABLE ADDRESS (
  Id             INTEGER PRIMARY KEY AUTOINCREMENT,
  Name           VARCHAR(50),
  Street_Address VARCHAR(200),
  City           VARCHAR(100),
  State_Code     CHARACTER(2),
  Zip            CHARACTER(5),
  FOREIGN KEY (State_Code) REFERENCES STATE (Code) ON DELETE SET NULL
);

CREATE TABLE STATE (
  Code CHARACTER(2) PRIMARY KEY,
  Name VARCHAR(40)
);

/**
 * Index creation.
 */
-- Create index on all primary keys and foreign keys to speed up query.
CREATE INDEX BOOK_INDEX ON BOOK (ISBN);
CREATE INDEX AUTHOR_INDEX ON AUTHOR (Name);
CREATE INDEX CATEGORY_INDEX ON CATEGORY (Name);
CREATE INDEX PUBLISHER_INDEX ON PUBLISHER (Name);
CREATE INDEX BOOK_AUTHOR_INDEX ON BOOK_AUTHOR (Book_ISBN, Author_Name);
CREATE INDEX BOOK_CATEGORY_INDEX ON BOOK_CATEGORY (Book_ISBN, Category_Name);
CREATE INDEX BOOK_PUBLISHER_INDEX ON BOOK_PUBLISHER (Book_ISBN, Publisher_Name);
CREATE INDEX CUSTOMER_INDEX ON CUSTOMER (Id, Address_Id, Credit_Card_Number);
CREATE INDEX ORDERS_INDEX ON ORDERS (Id, Customer_Id, Book_ISBN);
CREATE INDEX WAREHOUSE_INDEX ON WAREHOUSE (Id, Address_Id);
CREATE INDEX BOOK_STOCK_INDEX ON BOOK_STOCK (Book_ISBN, Warehouse_Id);
CREATE INDEX RATING_INDEX ON RATING (Customer_Id, Book_ISBN);
CREATE INDEX CREDIT_CARD_INDEX ON CREDIT_CARD (Credit_Card_Number, Billing_Address_Id);
CREATE INDEX ADDRESS_INDEX ON ADDRESS (Id, State_Code);
CREATE INDEX STATE_INDEX ON STATE (Code);

/**
 * View creation.
 */
-- A view that contains all the ratings for a book.
CREATE VIEW BOOK_RATING AS
  SELECT
    Title,
    (First_Name || ' ' || Last_Name) AS Customer_Name,
    Star_Count,
    Comment
  FROM BOOK
    JOIN RATING ON BOOK.ISBN = RATING.Book_ISBN
    JOIN CUSTOMER ON CUSTOMER.Id = RATING.Customer_Id;

-- The most gorgeous state from which people spend the most money.
CREATE VIEW MOST_GORGEOUS_STATE AS
  SELECT STATE.Name
  FROM ORDERS
    JOIN BOOK ON Book.ISBN = ORDERS.Book_ISBN
    JOIN CUSTOMER ON CUSTOMER.Id = ORDERS.Customer_Id
    JOIN ADDRESS ON ADDRESS.Id = CUSTOMER.Address_Id
    JOIN STATE ON STATE.Code = ADDRESS.State_Code
  GROUP BY State_Code
  ORDER BY sum(Price * Quantity)
    DESC
  LIMIT 1;

-- Categories loved by people from the most gorgeous state.
CREATE VIEW CATEGORIES_LOVED_BY_MOST_GORGEOUS_STATE AS
  SELECT CATEGORY.Name
  FROM ORDERS
    JOIN BOOK ON Book.ISBN = ORDERS.Book_ISBN
    JOIN BOOK_CATEGORY ON Book.ISBN = BOOK_CATEGORY.Book_ISBN
    JOIN CATEGORY ON CATEGORY.Name = BOOK_CATEGORY.Category_Name
    JOIN CUSTOMER ON CUSTOMER.Id = ORDERS.Customer_Id
    JOIN ADDRESS ON ADDRESS.Id = CUSTOMER.Address_Id
    JOIN STATE ON STATE.Code = ADDRESS.State_Code
  WHERE STATE.Code = (SELECT STATE.Code
                      FROM MOST_GORGEOUS_STATE
                        JOIN STATE ON MOST_GORGEOUS_STATE.Name = STATE.Name);
